export interface FileExtension {
  ext: string
  label: string
}

/**
 * A (reasonably) comprehensive list of common GitHub
 * file extensions + human-readable labels.
 */
export const FILE_EXTENSIONS: FileExtension[] = [
  { ext: '.js',      label: 'JavaScript (.js)' },
  { ext: '.jsx',     label: 'JavaScript JSX (.jsx)' },
  { ext: '.ts',      label: 'TypeScript (.ts)' },
  { ext: '.tsx',     label: 'TypeScript JSX (.tsx)' },
  { ext: '.mjs',     label: 'JavaScript Module (.mjs)' },
  { ext: '.cjs',     label: 'CommonJS Module (.cjs)' },
  { ext: '.py',      label: 'Python (.py)' },
  { ext: '.java',    label: 'Java (.java)' },
  { ext: '.rb',      label: 'Ruby (.rb)' },
  { ext: '.go',      label: 'Go (.go)' },
  { ext: '.rs',      label: 'Rust (.rs)' },
  { ext: '.php',     label: 'PHP (.php)' },
  { ext: '.html',    label: 'HTML (.html)' },
  { ext: '.htm',     label: 'HTML (.htm)' },
  { ext: '.css',     label: 'CSS (.css)' },
  { ext: '.scss',    label: 'SCSS (.scss)' },
  { ext: '.sass',    label: 'Sass (.sass)' },
  { ext: '.less',    label: 'Less (.less)' },
  { ext: '.md',      label: 'Markdown (.md)' },
  { ext: '.markdown',label: 'Markdown (.markdown)' },
  { ext: '.mdx',     label: 'Markdown JSX (.mdx)' },
  { ext: '.json',    label: 'JSON (.json)' },
  { ext: '.yml',     label: 'YAML (.yml)' },
  { ext: '.yaml',    label: 'YAML (.yaml)' },
  { ext: '.xml',     label: 'XML (.xml)' },
  { ext: '.sql',     label: 'SQL (.sql)' },
  { ext: '.sh',      label: 'Shell Script (.sh)' },
  { ext: '.bash',    label: 'Bash (.bash)' },
  { ext: '.zsh',     label: 'Zsh (.zsh)' },
  { ext: '.ps1',     label: 'PowerShell (.ps1)' },
  { ext: '.bat',     label: 'Batch (.bat)' },
  { ext: '.cmd',     label: 'Windows Script (.cmd)' },
  { ext: '.lua',     label: 'Lua (.lua)' },
  { ext: '.dart',    label: 'Dart (.dart)' },
  { ext: '.swift',   label: 'Swift (.swift)' },
  { ext: '.kt',      label: 'Kotlin (.kt)' },
  { ext: '.kts',     label: 'Kotlin Script (.kts)' },
  { ext: '.c',       label: 'C (.c)' },
  { ext: '.cpp',     label: 'C++ (.cpp)' },
  { ext: '.cc',      label: 'C++ (.cc)' },
  { ext: '.cxx',     label: 'C++ (.cxx)' },
  { ext: '.h',       label: 'C Header (.h)' },
  { ext: '.hpp',     label: 'C++ Header (.hpp)' },
  { ext: '.hxx',     label: 'C++ Header (.hxx)' },
  { ext: '.m',       label: 'Objective-C (.m)' },
  { ext: '.mm',      label: 'Obj-C++ (.mm)' },
  { ext: '.coffee',  label: 'CoffeeScript (.coffee)' },
  { ext: '.r',       label: 'R (.r)' },
  { ext: '.jl',      label: 'Julia (.jl)' },
  { ext: '.erl',     label: 'Erlang (.erl)' },
  { ext: '.ex',      label: 'Elixir (.ex)' },
  { ext: '.exs',     label: 'Elixir Script (.exs)' },
  { ext: '.fs',      label: 'F# (.fs)' },
  { ext: '.fsi',     label: 'F# Interface (.fsi)' },
  { ext: '.fsx',     label: 'F# Script (.fsx)' },
  { ext: '.cs',      label: 'C# (.cs)' },
  { ext: '.vb',      label: 'Visual Basic (.vb)' },
  { ext: '.groovy',  label: 'Groovy (.groovy)' },
  { ext: '.gradle',  label: 'Gradle (.gradle)' },
  { ext: '.dockerfile', label: 'Dockerfile' },
  { ext: '.tf',      label: 'Terraform (.tf)' },
  { ext: '.hcl',     label: 'HCL (.hcl)' },
  { ext: '.ini',     label: 'INI (.ini)' },
  { ext: '.toml',    label: 'TOML (.toml)' },
  { ext: '.conf',    label: 'Config (.conf)' },
  { ext: '.properties', label: 'Java Properties (.properties)' },
  { ext: '.env',     label: 'Env File (.env)' },
  { ext: '.lock',    label: 'Lock File (.lock)' },
]
